"""`adapters/imapb_codec.py` — ST 1201.3, checked against both documents' own worked examples.

WHY THE ASSERTIONS ARE WHAT THEY ARE
------------------------------------
Park 5's row states this park's risk in one sentence: *"the park where a wrong answer is least
visible: a float mapping applied with the wrong range yields a number rather than an exception"*.
Every choice in this file follows from that. A codec like this cannot be tested by round-tripping
itself — an implementation with `bPow` off by one round-trips perfectly and is wrong against every
other reader in the world. So the anchors are **figures neither this module nor this repository
chose**:

* ST 0601.14a prints an Example Software Value and an Example KLV Item for each of the fourteen
  items, and all fourteen are asserted;
* ST 1201.3 §10 prints two complete worked examples with intermediate constants and result tables,
  and both are asserted including the intermediates;
* §7.2.3's Table 2 fixes the special-value bit patterns, and each is asserted as a pattern rather
  than as whatever this implementation happens to emit.

**THE FIXTURES ARE NOT THE AUTHORITY EITHER.** They were generated by this codec, so a test that
only compared the codec to its own fixtures would be circular. The document-derived fixtures carry
the octets the DOCUMENT prints, transcribed by hand into the generator and asserted here against
the codec independently — and `test_the_document_fixtures_octets_are_the_documents_own` states
those octets a third time, as literals in this file, so a regenerated fixture cannot quietly move
one.

**NONE OF THE FOURTEEN IS WITNESSED.** The pinned stream stops at tag 65, so nothing here is
checked against a held octet, and `test_no_imapb_item_is_in_the_witnessed_set` asserts that
absence rather than leaving it as a thing the reader is trusted to remember. That is the whole of
why the rows stay `not yet`.
"""
from __future__ import annotations

import json
import math
import pathlib

import pytest

import synapse_cdm
from synapse_cdm.adapters import imapb_codec as C

PKG = pathlib.Path(synapse_cdm.__file__).resolve().parent
FIXTURES = PKG / "fixtures" / "klv" / "imapb"


def _fixtures():
    out = []
    for record in sorted(FIXTURES.glob("*.parsed.json")):
        data = json.loads(record.read_text())
        octets = (FIXTURES / f"{data['name']}.imapb").read_bytes()
        out.append((data, octets))
    return out


FIXTURE_SET = _fixtures()


# ------------------------------------------------------- the fourteen items, from ST 0601.14a

#: Transcribed from ST 0601.14a's §8.x Example rows, a THIRD time and by hand. The generator holds
#: the same table; if the two ever disagree one of them was edited without the document being
#: reopened, which is the failure this duplication exists to make loud.
DOCUMENT_EXAMPLES = {
    96:  (13898.5463, 3, "00D92A"), 103: (23456.24, 3, "2F921E"), 104: (23456.24, 3, "2F921E"),
    105: (23456.24,   3, "2F921E"), 109: (1.625,    3, "0001A0"), 112: (125.0,    2, "1F40"),
    113: (2150.0,     3, "05F500"), 114: (2154.5,   3, "05F740"), 117: (1.0,      2, "3E90"),
    118: (0.004176,   3, "3E8011"), 119: (-50.0,    2, "3B60"),   120: (72.0,     2, "4800"),
    132: (2400.0,     3, "0257C0"), 134: (55.0,     2, "3700"),
}


def test_the_fourteen_imapb_items_are_exactly_the_ledgers_enumeration():
    """The set, not just the members. Park 5 enumerates fourteen by the Format column."""
    assert sorted(C.IMAPB_ITEMS) == [96, 103, 104, 105, 109, 112, 113, 114,
                                     117, 118, 119, 120, 132, 134]
    assert sorted(DOCUMENT_EXAMPLES) == sorted(C.IMAPB_ITEMS)


@pytest.mark.parametrize("tag", sorted(DOCUMENT_EXAMPLES))
def test_each_items_own_worked_example_is_reproduced(tag):
    """Forward AND reverse, against the octets ST 0601.14a prints for that item.

    This is the check that would catch a wrong range, a wrong `bPow`, a dropped `Zoffset` or a
    little-endian conversion — each of which produces a well-formed number and none of which a
    round-trip test can see.
    """
    x, length, expected_hex = DOCUMENT_EXAMPLES[tag]
    assert C.encode_item(tag, length, x).hex().upper() == expected_hex

    back = C.decode_item(tag, bytes.fromhex(expected_hex))
    assert not isinstance(back, C.Special), f"tag {tag}'s worked example read as a signal"
    # The reverse map is lossy by construction (§8.3), so the assertion is on the quantisation
    # step rather than on equality — and the step is computed, not guessed at.
    _n, _u, a, b, _m = C.IMAPB_ITEMS[tag]
    step = 2.0 ** (math.ceil(math.log2(b - a)) - (8 * length - 1))
    assert abs(back - x) <= step, f"tag {tag}: {back} is further than one step ({step}) from {x}"


def test_tag_132s_example_is_only_right_in_megahertz():
    """Register entry KLV 20, asserted rather than described.

    The row prints '2.4 GHz' against a Units cell reading MHz. Both mappings are run here so the
    entry cannot go stale: the octets the row prints are 2400's, and 2.4's are something else.
    """
    assert C.encode_item(132, 3, 2400.0).hex().upper() == "0257C0"
    assert C.encode_item(132, 3, 2.4).hex().upper() != "0257C0"
    # And the wrong one is well-formed, which is the point of the entry.
    assert len(C.encode_item(132, 3, 2.4)) == 3


# ------------------------------------------------------------- ST 1201.3's own two examples

def test_st1201_example_3_including_its_intermediates():
    """§10 Example 3: IMAPA(-900, 19000, 0.5) -> L=3, then x=10.0 -> 232,960 = 0x038E00."""
    assert C.length_for_precision(-900.0, 19000.0, 0.5) == 3
    c = C.constants(-900.0, 19000.0, 3)
    assert c.b_pow == 15 and c.d_pow == 23      # the document's steps 1 and 2
    assert c.s_f == 2 ** 8 and c.s_r == 2 ** -8  # steps 3 and 4
    assert c.z_offset == 0.0                     # step 6, and it is zero here
    assert C.forward(-900.0, 19000.0, 3, 10.0) == 232_960
    assert C.encode(-900.0, 19000.0, 3, 10.0).hex().upper() == "038E00"
    # Table 6's other two rows.
    assert C.forward(-900.0, 19000.0, 3, -900.0) == 0
    assert C.forward(-900.0, 19000.0, 3, 0.0) == 230_400
    assert C.reverse(-900.0, 19000.0, 3, 232_960) == 10.0


def test_st1201_example_4_and_its_error_is_asserted_rather_than_round_tripped():
    """§10 Example 4: IMAPB(0.1, 0.9, 2). The reverse value is NOT the forward value.

    The document prints 0.499993896484375 and an error of 6.10e-6 for x=0.5. Asserting a round
    trip here would assert something ST 1201.3 explicitly says is false, so the printed value is
    asserted instead.
    """
    c = C.constants(0.1, 0.9, 2)
    assert c.b_pow == 0 and c.d_pow == 15 and c.s_f == 2 ** 15
    assert C.forward(0.1, 0.9, 2, 0.5) == 13_107
    assert C.encode(0.1, 0.9, 2, 0.5).hex().upper() == "3333"
    assert C.reverse(0.1, 0.9, 2, 13_107) == pytest.approx(0.499993896484375, abs=1e-15)
    assert C.reverse(0.1, 0.9, 2, 26_214) == pytest.approx(0.89998779296875, abs=1e-15)
    assert C.forward(0.1, 0.9, 2, 0.1) == 0


# ------------------------------------------------------------------ special values, §7.2.3

@pytest.mark.parametrize("kind,bits", [
    ("+Inf", (0, 0, 1)), ("-Inf", (1, 0, 1)), ("+QNaN", (0, 1, 0)), ("-QNaN", (1, 1, 0)),
    ("+SNaN", (0, 1, 1)), ("-SNaN", (1, 1, 1)), ("Reserved", (1, 0, 0)),
    ("UserDefined", (0, 0, 0)),
])
def test_table_2s_bit_patterns_decode_to_their_named_signal(kind, bits):
    """The pattern is built here from Table 2's own columns, not taken from the implementation."""
    sign, nan, b4 = bits
    length = 2
    n = 8 * length
    y = (0b11 << (n - 2)) | (sign << (n - 3)) | (nan << (n - 4)) | (b4 << (n - 5))
    got = C.decode(-900.0, 40000.0, y.to_bytes(length, "big"))
    assert isinstance(got, C.Special), f"{kind} decoded to a number: {got!r}"
    assert got.kind == kind


def test_a_signal_reverse_maps_to_a_finite_number_that_is_out_of_the_declared_range():
    """What a blind decoder actually gets, measured rather than asserted from expectation.

    THIS TEST WAS WRITTEN CLAIMING THE NAIVE VALUE IS PLAUSIBLE AND THAT IS FALSE — it is 800.0 on
    a range of 0..360, and the reason is structural rather than lucky: a Table 2 pattern sets the
    top two bits, so `y >= 3 * 2**(n-2)`, while the largest NORMAL value is about `2**(n-1)`. Every
    special pattern therefore reverse-maps above `b`. Recorded as the correction it is, because
    "the wrong answer looks fine" is park 5's stated risk and it is worth knowing exactly where
    that risk does and does not bite.

    **Where it does bite is one step later.** Reverse-mapping a signal raises nothing — it returns
    a finite float — and ST 1201.3 requires no range check of a decoder. So a decoder that skips
    §7.2.2 step 1 hands its caller 800.0 as a Platform Course Angle, and only a bound this codec's
    caller imposes stands between that and a heading two full turns off. The codec returns a
    `Special` instead, which is a refusal the type system carries.
    """
    octets = bytes.fromhex("C800")
    assert isinstance(C.decode(0.0, 360.0, octets), C.Special)

    naive = C.reverse(0.0, 360.0, 2, int.from_bytes(octets, "big"))
    assert isinstance(naive, float) and math.isfinite(naive), (
        "the naive reading must be a finite number — if it raised, a blind decoder would be safe "
        "and this whole branch would be unnecessary"
    )
    assert naive > 360.0, "a Table 2 pattern must reverse-map above b; see the docstring"
    # And the structural reason, asserted over every length so it is a property and not one case.
    for length in (1, 2, 3, 4):
        top_special = (0b11 << (8 * length - 2))
        assert C.reverse(0.0, 360.0, length, top_special) > 360.0


def test_the_msb_high_normal_value_is_not_read_as_a_signal():
    """Table 1 row 2: `1 0 0` is the maximum NORMAL value, not a signal.

    Only reachable when (b-a) is a power of two. A decoder testing the MSB alone loses the top of
    every such range, and it loses it silently.
    """
    octets = C.encode(0.0, 256.0, 2, 256.0)
    assert octets[0] & 0x80, "this fixture is pointless unless the MSB really is set"
    assert not (octets[0] & 0x40), "the second bit must be clear for Table 1 row 2"
    got = C.decode(0.0, 256.0, octets)
    assert not isinstance(got, C.Special)
    assert got == pytest.approx(256.0)


def test_special_values_round_trip_byte_exactly():
    """A signal re-emitted must be the octets it arrived as, payload included."""
    for kind in ("+Inf", "-Inf", "+SNaN", "UserDefined"):
        payload = 0x1234 if kind in ("+SNaN", "UserDefined") else 0
        sp = C.Special(kind, payload, 3)
        assert C.decode(-900.0, 40000.0, C.encode_special(sp)) == sp


# ------------------------------------------------------------------- Zoffset, §7.1.2 step 6

def test_zero_offset_makes_zero_land_on_an_integer_and_negatives_land_below_it():
    """§8.5's whole purpose, asserted as the property rather than as a constant."""
    a, b, length = -1000.0, 1000.0, 2
    zero = C.forward(a, b, length, 0.0)
    assert C.reverse(a, b, length, zero) == pytest.approx(0.0, abs=1e-9)
    for negative in (-0.001, -1.0, -50.0, -999.0):
        assert C.forward(a, b, length, negative) < zero, (
            f"{negative} maps to or above the zero point, which §8.5 forbids"
        )


def test_zero_offset_is_not_applied_to_an_all_positive_range():
    """The condition is `a < 0 and b > 0`. Tag 112's range is one that must not get the offset."""
    assert C.constants(0.0, 360.0, 2).z_offset == 0.0
    assert C.constants(0.0, 100.0, 2).z_offset == 0.0
    assert C.constants(-1000.0, 1000.0, 2).z_offset != 0.0 or True  # may legitimately be 0.0
    # The one that matters: an all-positive range must map its own minimum to exactly zero.
    assert C.forward(0.0, 360.0, 2, 0.0) == 0


# -------------------------------------------------------------------- §7.4, the wire's length

@pytest.mark.parametrize("length", [1, 2, 3, 4, 5, 6, 7, 8])
def test_the_constants_come_from_the_supplied_length(length):
    """Same item, eight widths, each decoding to within its own step of the value."""
    x = 125.0
    octets = C.encode_item(112, length, x)
    assert len(octets) == length
    back = C.decode_item(112, octets)
    step = 2.0 ** (math.ceil(math.log2(360.0)) - (8 * length - 1))
    assert abs(back - x) <= step


def test_a_fixed_width_decoder_would_be_wrong_and_this_says_by_how_much():
    """THE MUTATION for §7.4. Decode tag 112's two-octet example as if the width were fixed at 8.

    Not an exception — a number. 125° read with eight-octet constants is nowhere near 125.
    """
    two = C.encode_item(112, 2, 125.0)
    right = C.decode_item(112, two)
    wrong = C.reverse(0.0, 360.0, 8, int.from_bytes(two, "big"))
    assert right == pytest.approx(125.0)
    assert abs(wrong - 125.0) > 100.0, "the fixed-width mutant is not distinguishable here"


# --------------------------------------------------------------------------- refusals

def test_an_out_of_range_value_is_refused_rather_than_clamped():
    with pytest.raises(ValueError, match="outside IMAPB"):
        C.forward(0.0, 360.0, 2, 361.0)
    with pytest.raises(ValueError, match="outside IMAPB"):
        C.forward(0.0, 360.0, 2, -0.5)


def test_a_reversed_range_and_a_zero_length_are_refused():
    with pytest.raises(ValueError, match="a < b"):
        C.constants(360.0, 0.0, 2)
    with pytest.raises(ValueError, match="at least one octet"):
        C.constants(0.0, 360.0, 0)
    with pytest.raises(ValueError, match="zero-length"):
        C.decode(0.0, 360.0, b"")


def test_a_tag_that_is_not_imapb_is_refused_by_name():
    """Tag 5 is the Platform Heading Angle — a uint16, and the item most easily confused with 112."""
    with pytest.raises(KeyError, match="not one of the fourteen"):
        C.decode_item(5, bytes.fromhex("1F40"))


# --------------------------------------------------------------- the fixtures, and the scope

def test_the_fixture_set_is_present_and_bidirectional():
    assert len(FIXTURE_SET) >= 25, f"only {len(FIXTURE_SET)} fixtures found"
    ids = [d["fixture_id"] for d, _ in FIXTURE_SET]
    assert len(set(ids)) == len(ids), "fixture ids are not unique"
    for fid in ids:
        assert fid.startswith("f1c71201-0300-8000-8000-"), f"{fid} is off the UUID-v8 convention"


@pytest.mark.parametrize("case", FIXTURE_SET, ids=lambda c: c[0]["name"])
def test_every_fixture_decodes_as_its_record_says(case):
    data, octets = case
    assert octets.hex().upper() == data["octets_hex"]
    assert len(octets) == data["octet_count"]
    if data["kind"] == "special_value":
        got = C.decode(data["imapb_min"], data["imapb_max"], octets)
        assert isinstance(got, C.Special) and got.kind == data["special_kind"]
        assert C.encode_special(got) == octets, "a signal did not re-emit byte-exactly"
        return
    got = C.decode(data["imapb_min"], data["imapb_max"], octets)
    assert not isinstance(got, C.Special)
    assert got == pytest.approx(data["decodes_to"])
    if "software_value" in data:
        assert C.encode(data["imapb_min"], data["imapb_max"], len(octets),
                        data["software_value"]) == octets


def test_the_document_fixtures_octets_are_the_documents_own():
    """The fixtures' octets against this file's own transcription. Two sites, one document."""
    for tag, (_x, _length, expected_hex) in DOCUMENT_EXAMPLES.items():
        record = json.loads((FIXTURES / f"item_{tag}_document_worked_example.parsed.json").read_text())
        assert record["octets_hex"] == expected_hex, (
            f"tag {tag}'s fixture carries {record['octets_hex']} and ST 0601.14a prints "
            f"{expected_hex}"
        )
        assert record["tag"] == tag


def test_no_imapb_item_is_in_the_witnessed_set():
    """WHY THE FOURTEEN ROWS STAY `not yet`, asserted rather than remembered.

    The witnessed set is the 26 items the pinned stream carries and its highest tag is 65. Every
    one of the fourteen is above it, so this codec ships against no held octet — which is the
    scope contract's position and not this codec's defect.
    """
    highest_witnessed = 65
    assert min(C.IMAPB_ITEMS) > highest_witnessed, (
        "an IMAPB item is at or below the witnessed set's highest tag — if a second stream has "
        "landed, the fourteen rows' exit condition may now be reachable and this test is the "
        "wrong shape"
    )
