"""T16 / A13: the `dis7` codec and adapter against open-dis-python's own serialisation and parse.

Two halves. The always-on half needs nothing outside the repository: the packaged PDUs are the
bytes the handoff bundle records as OpenDIS-generated, the pin record states the independent
reading, the `reference` marker is registered, a missing checkout is a BLOCKED skip, and the
generator's scenarios are the packaged envelopes' twins. The live half carries
`@pytest.mark.reference` and asks for the pinned open-dis-python checkout through
`tests/dis7_reference_support.py`; without it each live test is SKIPPED with a reason beginning
`BLOCKED_EXTERNAL_EVIDENCE` — never passed. OpenDIS runs only in a child interpreter.
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import re
import struct
import subprocess
import sys

import pytest

from synapse_cdm import canonical, evidence
from synapse_cdm.adapters.dis7 import Dis7Adapter
from synapse_cdm.adapters.dis7_codec import Dis7Error, decode_pdu
from tests import dis7_reference_support as support
from tests.dis7_support import FIXTURES, STEMS, vector_bytes, vector_json

PIN_RECORD = FIXTURES / "spec" / "dis7_pin.json"

#: Length and SHA-256 of each packaged PDU, as the bundle's vector index records the
#: OpenDIS-generated bytes. Literals, never computed from the files.
RECORDED = {
    "equator_eastbound": (144, "c958233bda22e82385788584e0297d0e264ee2a0db94dc32838141925155ef1a"),
    "north_pole_stationary": (
        144, "e7354d35aab73b5e372c13dbf9c946ed57a53dadb1e11f3b218eadf402f00fc7"),
    "unprojectable_with_extensions": (
        160, "4397c9e4f90188a7eee7ceba7abad8a0a5c2c65c3108a3110e5157539507912d"),
}

ALL_EQUAL = ("3 vectors regenerated through open-dis-python "
             "732b6655bb47e34ccc73722eefe0f4706fd0032f: all equal the packaged files")


def _pin_record() -> dict:
    return json.loads(PIN_RECORD.read_text())


def _scenario(stem: str) -> dict:
    return json.loads(json.dumps(support.generator().SCENARIOS[stem]))


def _local_path_with_sha256(node) -> list:
    if isinstance(node, dict):
        found = [node] if "local_path" in node and "sha256" in node else []
        for value in node.values():
            found += _local_path_with_sha256(value)
        return found
    if isinstance(node, list):
        return [hit for value in node for hit in _local_path_with_sha256(value)]
    return []


# ======================================================================== always on

@pytest.mark.parametrize("stem", STEMS)
def test_t16_a13_packaged_vectors_are_the_recorded_opendis_bytes(stem):
    raw = vector_bytes(stem)
    size, sha = RECORDED[stem]
    assert len(raw) == size
    assert hashlib.sha256(raw).hexdigest() == sha
    rows = [row for row in _pin_record()["vectors"]["files"] if row["file"] == f"vectors/{stem}.dis"]
    assert len(rows) == 1, rows
    assert rows[0]["sha256"] == sha
    assert rows[0]["bytes"] == size


def test_t16_a13_pin_record_states_the_independent_reading():
    record = _pin_record()
    block = record["independent_reading_tool"]
    assert set(block) == {"status", "tool", "version", "taken_on", "environment", "what_it_shows"}
    if block["status"] == "TAKEN":
        assert re.fullmatch(r"\d{4}-\d{2}-\d{2}", block["taken_on"])
        assert set(block["environment"]) == {"python", "platform", "git", "opendis"}
        for key, value in block["environment"].items():
            assert isinstance(value, str) and value.strip(), key
        assert support.PIN in block["environment"]["opendis"]
    else:
        assert block["status"] == "BLOCKED_EXTERNAL_EVIDENCE"
        assert block["version"] is None
        assert block["taken_on"] is None
        assert block["environment"] is None
    assert _local_path_with_sha256(record) == []


def test_t16_a13_reference_marker_is_registered():
    lines = (pathlib.Path(__file__).resolve().parents[1] / "pytest.ini").read_text().splitlines()
    assert any(line.startswith("    reference:") for line in lines)
    assert any(line.startswith("    normative:") for line in lines)


def _empty_directory(tmp_path):
    return tmp_path


def _opendis_without_git(tmp_path):
    (tmp_path / "opendis").mkdir()
    (tmp_path / "opendis" / "dis7.py").write_text("")
    return tmp_path


@pytest.mark.parametrize("case, make, expected", [
    ("unset", None, "BLOCKED_EXTERNAL_EVIDENCE at step 'hook': SYNAPSE_CDM_OPENDIS_DIR is not set"),
    ("empty_directory", _empty_directory, "BLOCKED_EXTERNAL_EVIDENCE at step 'directory': "),
    ("no_git", _opendis_without_git, "BLOCKED_EXTERNAL_EVIDENCE at step 'record': "),
])
def test_t16_a13_blocked_reasons(case, make, expected, monkeypatch, tmp_path):
    if make is None:
        monkeypatch.delenv(support.ENV_VAR, raising=False)
    else:
        monkeypatch.setenv(support.ENV_VAR, str(make(tmp_path)))
    with pytest.raises(pytest.skip.Exception) as caught:
        support.checkout()
    if make is None:
        assert str(caught.value) == expected
    else:
        assert str(caught.value).startswith(expected), str(caught.value)


@pytest.mark.parametrize("stem", STEMS)
def test_t16_a13_generator_scenarios_are_the_packaged_twins(stem):
    module = support.generator()
    pdu = vector_json(stem, "envelope")["pdu"]
    assert list(module.SCENARIOS) == list(STEMS)
    assert module.REFERENCE_COMMIT == support.PIN
    scenario = module.SCENARIOS[stem]
    assert scenario["entity_id"] == pdu["entity_id"]
    assert scenario["force_id"] == pdu["force_id"]
    assert scenario["appearance"] == pdu["appearance"]
    assert scenario["capabilities"] == pdu["capabilities"]
    assert scenario["orientation"] == pdu["orientation_radians"]
    assert scenario["position"] == pdu["position_ecef_m"]
    assert scenario["exercise_id"] == pdu["header"]["exercise_id"]
    assert scenario["timestamp"] == pdu["header"]["timestamp"]
    assert scenario["status"] == pdu["header"]["status"]
    assert [scenario["entity_kind"], scenario["domain"], scenario["country"],
            scenario["category"]] == pdu["entity_type"][:4]
    assert struct.pack(">3f", *scenario["velocity"]) == struct.pack(">3f", *pdu["velocity_mps"])
    assert scenario["dead_reckoning_algorithm"] == int(pdu["dead_reckoning_hex"][:2], 16)
    assert (bytes([scenario["marking_character_set"]])
            + scenario["marking"].encode("ascii")).hex() == pdu["marking_hex"]
    assert [struct.pack(">BdIHB", *r).hex() for r in scenario["records"]] == \
        pdu["variable_parameters_hex"]
    assert not [name for name in sys.modules if name == "opendis" or name.startswith("opendis.")]


# ======================================================================== live

@pytest.mark.reference
@pytest.mark.parametrize("stem", STEMS)
def test_t16_a13_opendis_generates_each_packaged_vector(stem):
    directory = support.checkout()
    assert support.build(directory, _scenario(stem)) == vector_bytes(stem)


@pytest.mark.reference
def test_t16_a13_generator_script_reproduces_the_packaged_vectors():
    directory = support.checkout()
    done = subprocess.run([sys.executable, "-B", str(support.GENERATOR), str(directory)],
                          capture_output=True, text=True, env=support.child_env(), timeout=120)
    assert done.returncode == 0, done.stdout + done.stderr
    assert done.stdout.strip().splitlines()[-1] == ALL_EQUAL


@pytest.mark.reference
@pytest.mark.parametrize("stem", STEMS)
def test_t16_a13_opendis_parse_equals_decode_pdu_field_by_field(stem):
    directory = support.checkout()
    fields = support.parse(directory, vector_bytes(stem))["fields"]
    ours = decode_pdu(vector_bytes(stem))
    assert set(fields) == set(ours)
    assert set(fields["header"]) == set(ours["header"])
    for key in ours["header"]:
        assert fields["header"][key] == ours["header"][key], f"header.{key}"
    for key in ours:
        assert fields[key] == ours[key], key
    assert canonical.serialise(fields) == canonical.serialise(ours)


@pytest.mark.reference
@pytest.mark.parametrize("stem", STEMS)
def test_t16_a13_adapter_ingests_and_replays_opendis_bytes(stem):
    directory = support.checkout()
    raw = support.build(directory, _scenario(stem))
    adapter = Dis7Adapter.fixture_instance()
    objects = adapter.to_cdm(raw)
    assert len(objects) == 1
    assert [o.model_dump(mode="json") for o in objects] == vector_json(stem, "expected")
    assert adapter.from_cdm(objects) == raw


@pytest.mark.reference
@pytest.mark.parametrize("stem", STEMS)
def test_t16_a13_opendis_reparses_and_reserialises_the_replay(stem):
    directory = support.checkout()
    adapter = Dis7Adapter.fixture_instance()
    replayed = adapter.from_cdm(adapter.to_cdm(vector_bytes(stem)))
    answer = support.parse(directory, replayed)
    assert answer["reserialised_hex"] == replayed.hex()
    scenario = _scenario(stem)
    assert answer["fields"]["entity_id"] == scenario["entity_id"]
    assert answer["fields"]["force_id"] == scenario["force_id"]
    assert answer["fields"]["position_ecef_m"] == scenario["position"]


@pytest.mark.reference
def test_t16_a13_255_records_agree_in_both_directions():
    directory = support.checkout()
    scenario = _scenario("equator_eastbound")
    scenario["records"] = [[k, float(k), k * 65537, k, k] for k in range(255)]
    expected = [struct.pack(">BdIHB", k, float(k), k * 65537, k, k).hex() for k in range(255)]
    raw = support.build(directory, scenario)
    assert len(raw) == 4224
    assert raw[19] == 255
    adapter = Dis7Adapter.fixture_instance()
    objects = adapter.to_cdm(raw)
    assert len(objects) == 1
    assert objects[0].residual.data["pdu"]["variable_parameters_hex"] == expected
    assert adapter.from_cdm(objects) == raw
    answer = support.parse(directory, raw)
    assert answer["reserialised_hex"] == raw.hex()
    assert answer["fields"]["variable_parameters_hex"] == expected


@pytest.mark.reference
def test_t16_a13_type_67_is_refused():
    directory = support.checkout()
    scenario = _scenario("equator_eastbound")
    scenario["pdu_type"] = 67
    raw = support.build(directory, scenario)
    assert len(raw) == 144
    assert raw[2] == 67
    with pytest.raises(Dis7Error) as caught:
        Dis7Adapter.fixture_instance().to_cdm(raw)
    assert caught.value.code == "E_HEADER_UNSUPPORTED"
    assert caught.value.path == "byte[2]"


@pytest.mark.reference
def test_t16_a13_default_length_zero_is_refused():
    directory = support.checkout()
    scenario = _scenario("equator_eastbound")
    scenario["length"] = None
    raw = support.build(directory, scenario)
    assert raw[8:10] == b"\x00\x00"
    with pytest.raises(Dis7Error) as caught:
        Dis7Adapter.fixture_instance().to_cdm(raw)
    assert caught.value.code == "E_LENGTH_MISMATCH"
    assert caught.value.path == "byte[8]"


@pytest.mark.reference
def test_t16_a13_exercise_files_agree(tmp_path):
    directory = support.checkout()
    out = tmp_path / "exercise"
    spec = support.write_exercise(directory, out)
    assert spec == out / "opendis.json"
    report = evidence.exercise("dis7", json.loads(spec.read_text()), base=out)
    assert report.category.value == "independent_expected"
    assert len(report.results) == 6
    assert all(result.verdict == "AGREE" for result in report.results), report.results
    assert sorted(report.directions) == ["egress", "ingress"]
    assert report.peer.implementation == "open-dis-python"


@pytest.mark.reference
def test_t16_a13_pin_record_reading_was_taken():
    directory = support.checkout()
    block = _pin_record()["independent_reading_tool"]
    assert block["status"] == "TAKEN"
    assert block["environment"]["opendis"] == support.tool_versions(directory)["opendis"]
