import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * One autogenerated sidebar, ordered by `sidebar_position` in each page's own front matter.
 *
 * The alternative — listing every page id here — was rejected for one reason: the JSON Schema
 * Reference's pages are GENERATED, so a hardcoded list in this file would be another copy of
 * the schema inventory to keep in step, and the failure mode is a page that exists, builds,
 * and appears in no navigation. Ordering therefore lives next to the content it orders:
 *
 *   1  intro.mdx
 *   2  cdm/                    (_category_.json, hand-written)
 *   3  schema-reference/       (_category_.json, GENERATED — its index.mdx is the category
 *                               page by Docusaurus's category-index convention)
 *   4  writing-an-adapter.mdx
 *   5  changelog.mdx
 */
const sidebars: SidebarsConfig = {
  cdmSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
